name: Terraform Linter

on:
  push:
    branches: [main]
    paths: ['**.tf']
  pull_request:
    paths: ['**.tf']

jobs:
  terraform-linter:
    name: Check Terraform code for common mistakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -check -diff -recursive
